# Generated by Django 5.2.3 on 2025-07-11 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_generatedlesson_sourcematerial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='target_age',
            field=models.CharField(blank=True, choices=[('5-7', '5-7 tahun'), ('8-10', '8-10 tahun'), ('11-13', '11-13 tahun'), ('14-18', '14-18 tahun')], max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='teaching_style',
            field=models.CharField(blank=True, choices=[('formal', 'Formal & Terstruktur'), ('conversational', 'Percakapan Santai'), ('story-based', 'Berbasis Cerita')], max_length=20),
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.generatedlesson')),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('order', models.PositiveIntegerField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='QuizChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='courses.quizquestion')),
            ],
        ),
    ]
